# Generated by Django 3.1.1 on 2020-11-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='napkinss',
            name='Descrn',
        ),
        migrations.RemoveField(
            model_name='towels',
            name='Descr',
        ),
        migrations.AddField(
            model_name='napkinss',
            name='tickforbathbooln',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='napkinss',
            name='tickforembroiderybooln',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='napkinss',
            name='tickforfilamentbooln',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='napkinss',
            name='tickforsmoothbooln',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='towels',
            name='tickforbathboolt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='towels',
            name='tickforembroideryboolt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='towels',
            name='tickforfilamentboolt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='towels',
            name='tickforsmoothboolt',
            field=models.BooleanField(default=False),
        ),
    ]
